name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py37_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - conda=4.8.2=py37_0
  - conda-package-handling=1.6.0=py37h7b6447c_0
  - cryptography=2.8=py37h1ba5d50_0
  - idna=2.8=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_0
  - openssl=1.1.1d=h7b6447c_4
  - pip=20.0.2=py37_1
  - pycosat=0.6.3=py37h7b6447c_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.1.0=py37_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h0371630_2
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_1
  - ruamel_yaml=0.15.87=py37h7b6447c_0
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tqdm=4.42.1=py_0
  - urllib3=1.25.8=py37_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - appdirs==1.4.4
    - astroid==2.4.2
    - attrs==19.3.0
    - black==19.10b0
    - click==7.1.2
    - flake8==3.8.3
    - importlib-metadata==1.6.1
    - isort==4.3.21
    - lazy-object-proxy==1.4.3
    - mccabe==0.6.1
    - more-itertools==8.4.0
    - packaging==20.4
    - pathspec==0.8.0
    - pluggy==0.13.1
    - py==1.9.0
    - pycodestyle==2.6.0
    - pyflakes==2.2.0
    - pylint==2.5.3
    - pyparsing==2.4.7
    - pytest==5.4.3
    - regex==2020.5.14
    - toml==0.10.1
    - typed-ast==1.4.1
    - wcwidth==0.2.5
    - wrapt==1.12.1
    - zipp==3.1.0
prefix: /home/chris/miniconda3

